### ISSUE TITLE
AttributeError: 'ElementTree' object has no attribute 'getiterator'

### ISSUE THREAD

**Issue by ujjwalgarg100204** [gabrielbarbosanascimento/Up-Clock#27]
![image](https://user-images.githubusercontent.com/89966270/155267047-ad061049-9c0a-4a48-8247-1c39688e0991.png)
Text form:
$ up-clock
Traceback (most recent call last):
  File "/usr/bin/up-clock", line 48, in <module>
    up_clock.main()
  File "/usr/lib/python3/dist-packages/up_clock/__init__.py", line 45, in main
    window = UpClockWindow.UpClockWindow()
  File "/usr/lib/python3/dist-packages/up_clock_lib/Window.py", line 47, in __new__
    builder = get_builder('UpClockWindow')
  File "/usr/lib/python3/dist-packages/up_clock_lib/helpers.py", line 43, in get_builder
    builder.add_from_file(ui_filename)
  File "/usr/lib/python3/dist-packages/up_clock_lib/Builder.py", line 88, in add_from_file
    ele_widgets = tree.getiterator("object")
AttributeError: 'ElementTree' object has no attribute 'getiterator'

Quick info MX Linux:
[code]
System:    Kernel: 5.14.0-4mx-amd64 x86_64 bits: 64 compiler: gcc v: 10.2.1 
           parameters: BOOT_IMAGE=/boot/vmlinuz-5.14.0-4mx-amd64 
           root=UUID=<filter> ro quiet splash 
           init=/lib/systemd/systemd 
           Desktop: Xfce 4.16.0 tk: Gtk 3.24.24 info: xfce4-panel, plank wm: xfwm 4.16.1 vt: 7 
           dm: LightDM 1.26.0 Distro: MX-21_ahs_x64 Wildflower November 22  2021 
           base: Debian GNU/Linux 11 (bullseye) 
Machine:   Type: Laptop System: HP product: Victus by HP Laptop 16-e0xxx v: N/A serial: <filter> 
           Chassis: type: 10 serial: <filter> 
           Mobo: HP model: 88EC v: 80.56 serial: <filter> UEFI: AMI v: F.09 date: 07/16/2021 
Battery:   ID-1: BAT0 charge: 33.0 Wh (55.4%) condition: 59.6/59.6 Wh (100.0%) volts: 15.2 
           min: 15.4 model: HP Primary type: Li-ion serial: <filter> status: Discharging 
           cycles: 227 
CPU:       Info: 6-Core model: AMD Ryzen 5 5600H with Radeon Graphics bits: 64 type: MT MCP 
           arch: Zen 3 family: 19 (25) model-id: 50 (80) stepping: 0 microcode: A50000C cache: 
           L2: 3 MiB 
           flags: avx avx2 lm nx pae sse sse2 sse3 sse4_1 sse4_2 sse4a ssse3 svm bogomips: 79053 
           Speed: 2755 MHz min/max: 1200/3300 MHz boost: enabled Core speeds (MHz): 1: 2755 
           2: 2794 3: 1135 4: 1148 5: 1197 6: 1197 7: 1779 8: 1261 9: 1555 10: 1332 11: 1296 
           12: 1297 
           Vulnerabilities: Type: itlb_multihit status: Not affected 
           Type: l1tf status: Not affected 
           Type: mds status: Not affected 
           Type: meltdown status: Not affected 
           Type: spec_store_bypass 
           mitigation: Speculative Store Bypass disabled via prctl and seccomp 
           Type: spectre_v1 mitigation: usercopy/swapgs barriers and __user pointer sanitization 
           Type: spectre_v2 mitigation: Full AMD retpoline, IBPB: conditional, IBRS_FW, STIBP: 
           always-on, RSB filling 
           Type: srbds status: Not affected 
           Type: tsx_async_abort status: Not affected 
Graphics:  Device-1: NVIDIA GA107M [GeForce RTX 3050 Mobile] vendor: Hewlett-Packard 
           driver: nvidia v: 510.54 alternate: nouveau,nvidia_drm bus-ID: 01:00.0 
           chip-ID: 10de:25a5 class-ID: 0300 
           Device-2: AMD Cezanne vendor: Hewlett-Packard driver: amdgpu v: kernel 
           bus-ID: 06:00.0 chip-ID: 1002:1638 class-ID: 0300 
           Device-3: Luxvisions Innotech Limited HP Wide Vision HD Camera type: USB 
           driver: uvcvideo bus-ID: 1-3:2 chip-ID: 30c9:000e class-ID: 0e02 
           Display: x11 server: X.Org 1.20.13 compositor: picom v: git-c4107 driver: 
           loaded: amdgpu,ati,nvidia unloaded: fbdev,modesetting,nouveau,vesa alternate: nv 
           display-ID: :0.0 screens: 1 
           Screen-1: 0 s-res: 1920x1080 s-dpi: 96 s-size: 508x285mm (20.0x11.2") 
           s-diag: 582mm (22.9") 
           Monitor-1: eDP res: 1920x1080 hz: 60 dpi: 137 size: 355x200mm (14.0x7.9") 
           diag: 407mm (16") 
           OpenGL: renderer: AMD RENOIR (DRM 3.42.0 5.14.0-4mx-amd64 LLVM 12.0.1) 
           v: 4.6 Mesa 21.2.5 direct render: Yes 
Audio:     Device-1: NVIDIA vendor: Hewlett-Packard driver: snd_hda_intel v: kernel 
           bus-ID: 01:00.1 chip-ID: 10de:2291 class-ID: 0403 
           Device-2: AMD Renoir Radeon High Definition Audio vendor: Hewlett-Packard 
           driver: snd_hda_intel v: kernel bus-ID: 06:00.1 chip-ID: 1002:1637 class-ID: 0403 
           Device-3: AMD ACP/ACP3X/ACP6x Audio Coprocessor 
           vendor: Hewlett-Packard Raven/Raven2/FireFlight/Renoir Processor 
           driver: snd_rn_pci_acp3x v: kernel alternate: snd_pci_acp3x bus-ID: 06:00.5 
           chip-ID: 1022:15e2 class-ID: 0480 
           Device-4: AMD Family 17h/19h HD Audio vendor: Hewlett-Packard driver: snd_hda_intel 
           v: kernel bus-ID: 06:00.6 chip-ID: 1022:15e3 class-ID: 0403 
           Sound Server-1: ALSA v: k5.14.0-4mx-amd64 running: yes 
           Sound Server-2: PulseAudio v: 14.2 running: yes 
Network:   Device-1: Realtek RTL8111/8168/8411 PCI Express Gigabit Ethernet 
           vendor: Hewlett-Packard driver: r8169 v: kernel port: e000 bus-ID: 02:00.0 
           chip-ID: 10ec:8168 class-ID: 0200 
           IF: eth0 state: down mac: <filter> 
           Device-2: Realtek RTL8852AE 802.11ax PCIe Wireless Network Adapter 
           vendor: Hewlett-Packard driver: rtw89_pci v: N/A modules: rtw89pci,wl port: d000 
           bus-ID: 03:00.0 chip-ID: 10ec:8852 class-ID: 0280 
           IF: wlan0 state: up mac: <filter> 
Bluetooth: Device-1: Realtek Bluetooth Radio type: USB driver: btusb v: 0.8 bus-ID: 1-4:3 
           chip-ID: 0bda:2852 class-ID: e001 serial: <filter> 
           Report: hciconfig ID: hci0 rfk-id: 1 state: up address: <filter> bt-v: 3.0 lmp-v: 5.2 
           sub-v: a0cd hci-v: 5.2 rev: d9a8 
           Info: acl-mtu: 1021:6 sco-mtu: 255:12 link-policy: rswitch hold sniff park 
           link-mode: slave accept service-classes: rendering, capturing, object transfer, audio 
Drives:    Local Storage: total: 476.94 GiB used: 138.64 GiB (29.1%) 
           SMART Message: Unable to run smartctl. Root privileges required. 
           ID-1: /dev/nvme0n1 maj-min: 259:0 vendor: Western Digital 
           model: PC SN730 SDBPNTY-512G-1006 size: 476.94 GiB block-size: physical: 512 B 
           logical: 512 B speed: 31.6 Gb/s lanes: 4 type: SSD serial: <filter> rev: HPS2 
           temp: 37.9 C scheme: GPT 
Partition: ID-1: / raw-size: 100 GiB size: 97.87 GiB (97.87%) used: 24.18 GiB (24.7%) fs: ext4 
           dev: /dev/nvme0n1p2 maj-min: 259:2 
           ID-2: /boot/efi raw-size: 512 MiB size: 511 MiB (99.80%) used: 32 MiB (6.3%) fs: vfat 
           dev: /dev/nvme0n1p1 maj-min: 259:1 
Swap:      Alert: No swap data was found. 
Sensors:   System Temperatures: cpu: 56.0 C mobo: N/A gpu: amdgpu temp: 46.0 C 
           Fan Speeds (RPM): N/A 
Repos:     Packages: 2140 note: see --pkg apt: 2129 lib: 1078 flatpak: 0 snap: 11 
           No active apt repos in: /etc/apt/sources.list 
           No active apt repos in: /etc/apt/sources.list.d/apandada1-ubuntu-up-clock-jammy.list 
           Active apt repos in: /etc/apt/sources.list.d/debian-stable-updates.list 
           1: deb http://deb.debian.org/debian/ bullseye-updates main contrib non-free
           Active apt repos in: /etc/apt/sources.list.d/debian.list 
           1: deb http://deb.debian.org/debian/ bullseye main contrib non-free
           2: deb http://security.debian.org/debian-security/ bullseye-security main contrib non-free
           Active apt repos in: /etc/apt/sources.list.d/mx.list 
           1: deb http://mxrepo.com/mx/repo/ bullseye main non-free
           2: deb http://mxrepo.com/mx/repo/ bullseye ahs
           Active apt repos in: /etc/apt/sources.list.d/teams.list 
           1: deb [arch=amd64] https://packages.microsoft.com/repos/ms-teams/ stable main
           Active apt repos in: /etc/apt/sources.list.d/vscode.list 
           1: deb [arch=amd64,arm64,armhf] http://packages.microsoft.com/repos/code/ stable main
Info:      Processes: 326 Uptime: 3h 18m wakeups: 2 Memory: 7.12 GiB used: 4.98 GiB (69.9%) 
           Init: systemd v: 247 runlevel: 5 default: 5 tool: systemctl Compilers: gcc: 10.2.1 
           alt: 10 Shell: quick-system-in default: Bash v: 5.1.4 running-in: quick-system-in 
           inxi: 3.3.06 
[/code]

**Comment by apandada1** [comment]
This issue is present in Ubuntu 21.10+, but not in Ubuntu 20.04. May be due to some incompatibility with recent versions of python. I will look into it.

**Comment by apandada1** [comment]
Fixed in https://github.com/gabrielbarbosanascimento/Up-Clock/commit/97c4dfffb5d5b7d6ee7cb44bbd4b6f82493a3d18
The fixed version for Ubuntu 22.04+ is available in the Launchpad PPA.
